# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bcdf1a499934b71ea187325aae14878244f6d8b27a275fce84c3ef802fea07e5f9a574f3593c3e12571f66fed8f18fd73e59740b0257bf7c97b9e2556de3ff8

test:
  secret_key_base: d944a7162595eb1978176541ac9b7ae1c9c31b800497a765358d87ba113505b0b12cb23bf3ac0c13ac17085c6dab88979b70063c341fc693ee5d4f6f0945145c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
